### ISSUE TITLE
Issue deploying functions to firebase cloud

### ISSUE THREAD

**Issue by jayshildave1983** [firebase/mlkit-custom-image-classifier#22]
While deploying function we are seeing below errors
`
src/check_operations_progress.ts:41:22 - error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'string[]' is not assignable to type 'string'.

41     if (!isValidType(operationType)) {
                        ~~~~~~~~~~~~~

src/generate_label_file.ts:35:46 - error TS2345: Argument of type 'string | string[] | ParsedQs | ParsedQs[] | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.

35       const labelsFile = await generateLabel(dataset);
                                                ~~~~~~~


Found 2 errors.
`
Could this be related to the npm configuration or something.

The complete log is below:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.5
3 info using node@v12.18.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle functions@~prebuild: functions@
6 info lifecycle functions@~build: functions@
7 verbose lifecycle functions@~build: unsafe-perm in lifecycle true
8 verbose lifecycle functions@~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/jayshildave/Downloads/mlclass_new/mlkit-custom-image-classifier/functions/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jayshildave/Library/Android/sdk/tools:/Users/jayshildave/Library/Android/sdk/platform-tools:/Users/jayshildave/Documents/gradle-6.0/bin:/Users/jayshildave/Documents/gradle-6.0/bin
9 verbose lifecycle functions@~build: CWD: /Users/jayshildave/Downloads/mlclass_new/mlkit-custom-image-classifier/functions
10 silly lifecycle functions@~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle functions@~build: Returned: code: 2  signal: null
12 info lifecycle functions@~build: Failed to exec build script
13 verbose stack Error: functions@ build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid functions@
15 verbose cwd /Users/jayshildave/Downloads/mlclass_new/mlkit-custom-image-classifier/functions
16 verbose Darwin 19.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.18.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 2
22 error functions@ build: `tsc`
22 error Exit status 2
23 error Failed at the functions@ build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

is there any specific updates to certain version which is required for this?

**Comment by jayshildave1983** [comment]
Was able to fix the issue by updating both places to below
`dataset as string`
Instead of passing just dataset cast it to be a string.

Closing based on above.
